[workspace]
name = "vrp-tfm"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.10.*"
numpy = "*"
pandas = ">=2.3.3,<3"
sqlalchemy = ">=2.0.46,<3"
pyyaml = ">=6.0.3,<7"
oracledb = ">=3.4.2,<4"
folium = ">=0.20.0,<0.21"
request = ">=2.83.1,<3"
streamlit = ">=1.54.0,<2"
streamlit-folium = ">=0.26.1,<0.27"
openpyxl = ">=3.1.5,<4"

[pypi-dependencies]
ortools = "*"
customtkinter = ">=5.2.2, <6"


